export enum LEGALIZED_TABLE {
  TABLE_NAME = "LGZ_LEGALIZADOS",
  ID = "LGZ_CODIGO",
  ANNOUNCEMENT_ID = "LGZ_CONVOCATORIA",
  COMMUNE_FUND_ID = "LGZ_FONDO_COMUNA",
  RESOURCE = "LGZ_RESOURCE",
  FIDUCIARY_ID = "LGZ_FIDUCIA",
  ORDER = "LGZ_ORDEN",
  USER_MODIFIED = "LGZ_USUARIO_MODIFICO",
  UPDATED_AT = "LGZ_FECHA_MODIFICO",
}
