export enum PERMISSIONS {
  // =============================================
  // ABSORTION PERCENTAGE
  ABSORTION_PERCENTAGE = "FONDOS_PORCENTAJE_ABSORCION",
  FUNDS_ABSORTION_PERCENTAGE_CREATE = "FONDOS_PORCENTAJE_ABSORCION_CREAR",
  FUNDS_ABSORTION_PERCENTAGE_UPDATE = "FONDOS_PORCENTAJE_ABSORCION_EDITAR",
  FUNDS_ABSORTION_PERCENTAGE_DELETE = "FONDOS_PORCENTAJE_ABSORCION_ELIMINAR",
  FUNDS_ABSORTION_PERCENTAGE_DOWNLOAD_XLSX = "FONDOS_PORCENTAJE_ABSORCION_XLSX",
  FUNDS_ABSORTION_PERCENTAGE_CONSULT = "FONDOS_PORCENTAJE_ABSORCION_CONSULTAR",
  // =============================================
  FUNDS_LEGALIZED_CONSULT = "FONDOS_LEGALIZADO_CONSULTAR",
  FUNDS_LEGALIZED_UPDATE = "FONDOS_LEGALIZADO_EDITAR",
  FUNDS_LEGALIZED_DOWNLOAD_XLSX = "FONDOS_LEGALIZADO_XLSX",
}
